import "./globals.css";
import type { Metadata } from "next";
import { poppins } from "./libs/utils/fonts";
import { cxm } from "./libs/helpers";
import { ChildrenProps } from "danimahdani";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en" className={cxm(poppins.variable)} suppressHydrationWarning>
      <body>
        <NextTopLoader color="#F4C2AB" showSpinner={false} />
        <div className={cxm("mix-h-screen w-full")}>{children}</div>
      </body>
    </html>
  );
}
